env:
    MANIFEST: https://github.com/SuperiorOS/manifest.git -b thirteen
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest.git
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true && export SELINUX_IGNORE_NEVERALLOWS=true
    EXTEA_CMD1: export WITH_GAPPS=true
    LUNCH_COMBO: superior_${DEVICE}-userdebug
    OUTPUT: S*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[d2dd0bb296948116fac1218dea0d7a3af1e2aacd2d151c8d15d4e4508b80ca3c0758ec94de1bfd411a1ae4b2f8517266]
    URI: https://downloads.sourceforge.net/project/fleur/ccache/ccache.tar.gz?ts=gAAAAABkiC192A9uXyDcQKJ_PmavyYVEH-1BU5FTdiDSuhORUB-uPG7B4ZGBjQjwxLYetWCg2WOhXkGtwCyfXPQ08yoREf6Llg%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ffleur%2Ffiles%2Fccache%2Fccache.tar.gz%2Fdownload
    ROM_U: 1
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
