env:
    MANIFEST: https://github.com/StatiXOS/android_manifest.git -b tm-qpr3
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest.git
    TARGET: statix
    LUNCH_COMBO: statix_${DEVICE}-userdebug
    OUTPUT: sta*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[65f39ad35028565d747a3510a29171d410643f879f1e587ecaf4530bf32b9602d1fd44a68316e0bdfa5260ecf1f584f6]
    URI: https://abdullah.al-noman.workers.dev/0:/ccache.tar.gz
    ROM_U: 1
task:
  name: "build"
  timeout_in: 120m
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
