env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: R*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[72f5f86617bdbce7d0624241a91bdb2aa74a559018877b891dc83c1701ff368fbb8d88636957cd6345244c2d62ec1d8a]
    URI: https://realme-x.srasidda-ks.workers.dev/0:/ci/ccache.tar.gz.zip
    ROM_U: 1
    

task:
  name: "build"
  timeout_in: 120m
 
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
