env:
    MANIFEST: https://github.com/Octavi-Staging/manifest.git -b thirteen --depth=1
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: octavi_${DEVICE}-userdebug
    OUTPUT: O*.zip
    CLO: idl:ci
    CLO_1: ENCRYPTED[!b71a13e9e965a996b143f7e4b733cdc03d97a3fd55cd33ad578c2c386e51c6bd1fa087132ddb28de65c75a786a00142a!]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Octavi/ccache.tar.gz/download
    ROM_U: 1
    

task:
  name: "build"
  timeout_in: 240m
 
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
