env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs
    DEVICE: RMX1901
    OEM: realme
    LOCAL_MANIFEST: https://github.com/Shravan55555/local_manifest.git
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: r*.zip
    CLO: RMX1901
    CLO_1: ENCRYPTED[!6f655cf874276175b972fd352a1965217cdf543f495270059a951f33c17b58ee08ffa8a1aa43d69ac4edeefa9a49fac3!]
    URI: https://sourceforge.net/projects/fleur/files/ccache/RisingOS/ccache.tar.gz/download
    ROM_U: 1
    

task:
  name: "build"
  timeout_in: 120m
 
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
